
enum Tokens {
    TTEOF,
    TCD22,
    TCONS, TTYPS, TTDEF, TARRS,
    TMAIN,
    TBEGN, TTEND, TARAY, TTTOF, TFUNC,
    TVOID,
    TCNST, TINTG, TFLOT, TBOOL, TTFOR,
    TREPT,
    TUNTL, TIFTH, TELSE, TELIF, TINPT, TPRNT,
    TPRLN, TRETN, TNOTT, TTAND, TTTOR, TTXOR,
    TTRUE, TFALS,
    TCOMA, TLBRK, TRBRK, TLPAR, TRPAR,
    TEQUL,
    TPLUS, TMINS, TSTAR, TDIVD, TPERC,
    TCART,
    TLESS, TGRTR, TCOLN, TSEMI, TDOTT,
    TLEQL,
    TGEQL, TNEQL, TEQEQ, TPLEQ, TMNEQ, TSTEQ,
    TDVEQ,
    TIDEN, TILIT, TFLIT, TSTRG, TUNDF
};


public class Token {
}
