name: Build And Run Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: make
      run: cd src && javac A2.java
    - name: run simple
      run: cd src && java A2 ../data/simple.txt
    - name: run factorial
      run: cd src && java A2 ../data/CD22Source/factorial.txt
    - name: run fibonacci
      run: cd src && java A2 ../data/CD22Source/fibonacci.txt
    - name: run points
      run: cd src && java A2 ../data/CD22Source/points.txt
    - name: run semantic
      run: cd src && java A2 ../data/CD22Source/semantic.txt
    - name: run simple
      run: cd src && java A2 ../data/CD22Source/simple.txt
    - name: run simple_array
      run: cd src && java A2 ../data/CD22Source/simple_array.txt
    - name: run simple_function
      run: cd src && java A2 ../data/CD22Source/simple_function.txt
    - name: run simple_variable
      run: cd src && java A2 ../data/CD22Source/simple_variable.txt
    - name: run boolean
      run: cd src && java A2 ../data/general_tests/parser/boolean.txt
    - name: run expression
      run: cd src && java A2 ../data/general_tests/parser/expression.txt
    - name: run repeat
      run: cd src && java A2 ../data/general_tests/parser/repeat.txt
